### ISSUE TITLE
Not able to change Panel Number or Panel Name (etc on Basic Config Page)

### ISSUE THREAD

**Issue by l-arnold** [temcocontrols/T3000_Building_Automation_System#342]
Windows 7 Machine.
Feb 1, 2021 build
Feb 23, 2021 build

Neither able to change the Panel Number or Panel name in T3000.
Separate (Windows 2016 Server) Machine running May 29, 2020 T-3000 is able to change these.

Feb 23 2021 did fix WIFI configuration dysfunction in Feb 1 2021 build with T3-LB.

For now I am maintaining the May 2020 version specifically so I change Panel Names and Panel Numbers.

**Comment by Fance** [comment]
Thanks for your feedback . Just now, I fixed the problem.I'm going to Release a T3000 first, and then I'm going to write the code for that Release and Pull the request to the Master later.

**Comment by l-arnold** [comment]
Ok.  Post here when that is completed and I will give it a spin.

**Comment by l-arnold** [comment]
Also,  is there a repository for dated T3000 builds that can be accessed online?  Somewhat complicated and this is an example of where it could be helpful.  Not easy simply to "go back one" build or go to a certain date etc.  I am sure it could be done with Github but that requires active Gets and Pulls.

**Comment by l-arnold** [comment]
Starting to have access to panel name.  Getting timeouts though still  (new T3000 2-23-2021 and new firmware - T3-OEM 60.1)

**Comment by l-arnold** [comment]
I can type (added -b) inside control panel but it does not update in the building tree (Local Network) - getting a "Write into device timeout!"
![Screenshot 2021-03-02 15 34 48](https://user-images.githubusercontent.com/5673448/109725075-d4fe0100-7b6d-11eb-9e9d-2f2bf0f26e48.png)

and

![Screenshot 2021-03-02 15 40 50](https://user-images.githubusercontent.com/5673448/109725101-dcbda580-7b6d-11eb-86cf-a151fdb58d24.png)

**Comment by Fance** [comment]
Health in the status bar is red and T3000 is disconnected from this device.I suggest you click on the device and reconnect.The read and write operations time out until the connection is re-established.
