### ISSUE TITLE
T3000 must be restarted to read the new firmware (MCU) version

### ISSUE THREAD

**Issue by l-arnold** [temcocontrols/T3000_Building_Automation_System#344]
I've just had this happen twice today.  (perhaps 4 times)

Updated firmware on T3-OEM to 60.1 from 54.x.

(One went smooth, one needed lots of work and only in the end worked on Bacnet-RS485 SUB setting)

But after ISP Tool supported well, even closing and reopening the config for the controller was showing MCU 54.x.
After restarting T3000, the config showed as 60.1.  It would be good if there were a "refresh" button to get current data in T3000 from the controller.  Restarting T3000 was not an obvious solution (perhaps it was)

**Comment by Fance** [comment]
When the device completes the firmware update, the device disconnects from the T3000 connection.The list of devices to the left of T3000 will show a red X, and the Health in the status bar will most likely be 0%.You need to manually re-click the device to establish the connection.
