### ISSUE TITLE
RS-485 method changes when moving from USB to Wifi T3-OEM

### ISSUE THREAD

**Issue by l-arnold** [temcocontrols/T3000_Building_Automation_System#345]
With some difficulty I was able to update firmware on a T3-OEM (after one before went without problem).

I needed to set RS485 SUB to BACNET
Rescan
this gave me a new Panel ID (had been 10, became 37)

With ISP Tool, I was able to write on Serial Port, New number 37 and it worked.

However, then I engaged Wifi.  Wifi moved the controller into the local Network and off of the Com port.

I was very suprised to find that the RS485 Sub setting then went to Modbus Slave  (perhaps an earlier setting).  There seem to be different "identities" that get shown and hidden as active connection changes on any controller. 

Somewhat complicated to follow.  Lots to look out for.

**Comment by Fance** [comment]
If the device is also connected to the network (Ethernet or WiFi) and also uses RS485 connection.T3000 show  the device list using the network in preference.At the same time, you can still use third-party software to access the device via RS485.
