### ISSUE TITLE
T3000 Software Crashes while Opening Programming Window

### ISSUE THREAD

**Issue by lonerzzz** [temcocontrols/T3000_Building_Automation_System#427]
I am hitting a problem where the T3000 software crashes when I select the first program and then hit the 'programming' button. The programming page needs the following:

1) A way to clear a program slot that cannot be loaded
2) A fix to allow the program to be loaded.

**Comment by Fance** [comment]
We will add methods to clear the exception code so that the user can open normally. If we can restore the code without crashing it, we will do so.Thanks！

**Comment by lonerzzz** [comment]
I can confirm that the Jul 14 2023 T3000 load resolves the current issue. This issue can be closed.
