### ISSUE TITLE
TStat10 Programming timeout is too long

### ISSUE THREAD

**Issue by lonerzzz** [temcocontrols/T3000_Building_Automation_System#430]
When a TStat10 programming timeout occurs, the timeout takes about a minute to happen. I should take no more than 10 seconds to timeout.

**Comment by MauriceDuteau** [comment]
Sorry to respond with a question but what sort of timeout are we talkikng about please. Bacnet, Modbus, RS485, IP, Wifi....

**Comment by lonerzzz** [comment]
That is what I am referring to.

**Comment by lonerzzz** [comment]
This issue continues to waste a lot of our time during development.

**Comment by MauriceDuteau** [comment]
We checked and rechecked, the software waits three seconds before declaring a timeout. If you are seeing longer than that then perhaps the communications health is not good. You can do a wireshark capture and perhaps we can spot something from that.

**Comment by lonerzzz** [comment]
This is what we get on the program window:
![image](https://github.com/temcocontrols/T3000_Building_Automation_System/assets/3473145/85f5c42a-5f70-4f21-84b2-ac3f0ad8e23a)

This is the timeout message that we get:
![image](https://github.com/temcocontrols/T3000_Building_Automation_System/assets/3473145/e253ca4b-fdc3-4d77-b80a-cabc27c9dc4d)

This is the messaging in Wireshark:
![image](https://github.com/temcocontrols/T3000_Building_Automation_System/assets/3473145/29687138-1cf5-4865-b3d5-0150004d99c7)

Nothing stands out as a message with a timeout error.

**Comment by Fance** [comment]
I'd be happy to help you with that. There are many reasons for this problem, such as wifi signal quality, firmware version that needs to be updated, software version that needs to be updated, ip address conflict, some parameter Settings of the device are wrong, and so on.
If possible, I'd like to remotely assist you in identifying the root cause of the problem. You can contact us at sales3 at
 temcocontrols.com and we can schedule a time for remote help you.

**Comment by MauriceDuteau** [comment]
Fandu confirms again that T3000 waits three seconds and retries, It will do this three times and then put up the timeout message after  9 seconds total. 

Fandu: You could make things a little more responsive by showing the three retires at least. 
            Do make sure its both RS485 and Ethernet that have this similar timeout setting please.

**Comment by lonerzzz** [comment]
> I'd be happy to help you with that. There are many reasons for this problem, such as wifi signal quality, firmware version that needs to be updated, software version that needs to be updated, ip address conflict, some parameter Settings of the device are wrong, and so on. If possible, I'd like to remotely assist you in identifying the root cause of the problem. You can contact us at sales3 at temcocontrols.com and we can schedule a time for remote help you.

Hi Fance, would it be possible to add or enable logging for the T3000 a to show what is happening. I could then send you the log file after several runs. This would be easier because without addition capture of details, I suspect that you would see exactly what I do - just a frozen editor screen followed by a timeout popup window.

**Comment by MauriceDuteau** [comment]
You could show us the communications tab along the bottom status line of T3000, it shows the communications health. 

Also let's just confirm from looking at your log that you are using Wifi. T3000 can be finicky when there's several adapters on your PC, temporarily disable all VPNs, virtual adapters and the wired Adapter and give that a shot. 

If you have an RS485 dongle you could give it a try to connect over RS485.

**Comment by lonerzzz** [comment]
The communication tab shows no increment in the error count when this situation occurs. The error count remains unchanged before and after the timeout. This was observed 6 times in the last little bit and every time no error increment occurred.

There are no virtual adapters or VPN connections. I tried limiting to the single ethernet connection and the issue remained unchanged. The computer is using ethernet to the WiFi router and the WiFi router connects to the TStat10.

**Comment by MauriceDuteau** [comment]
OK, it starts to come back to me. The wifi modules in use on the original version Tstat10 are not good. Fandu will see what we can do to timeout earlier. Itll be best to program over RS485 to start, then make small edits only over wifi. Sorry about this. 

Also we have a new wifi module in the works, real soon now.

**Comment by lonerzzz** [comment]
Based on what I am seeing with no error messaging, I am not sure it is possible to conclude that the issue is related to the networking. I would suggest that printing activity information to what is now just the compiler error window might be inciteful. It would certainly make for a more user friendly interface.

Something like the following would be useful user feedback regardless of the error cause:
2023-10-11 09:17:21 Compiling program
2023-10-11 09:17:23 Compiled size: 1671 bytes
2023-10-11 09:17:24 Connecting with unit
2023-10-11 09:17:25 Sending program
2023-10-11 09:17:27 Send complete.

**Comment by Fance** [comment]
192.168.0.115 is my Tstat10 wifi device .
I have tested for many times, and there is no problem with Tstat10 wifi communication, which is very smooth in my place. The size I read is 1377 bytes. I suspect that your wifi communication quality is not very good, I still hope to be able to help remotely, or you can send the entire wireshark communication, capture the packet and upload it to me for analysis. Thank you very much!
![image](https://github.com/temcocontrols/T3000_Building_Automation_System/assets/3907266/7bc34eca-8e9a-44fd-ac0d-ba788210a312)

**Comment by Fance** [comment]
The entire reading process of program I tested took only 0.9 seconds. All you are encountering may be other problems, I hope to get more useful information to help you solve your confusion

**Comment by lonerzzz** [comment]
I doubt it is the WiFi at this point because no messaging is ever in progress in Wireshark when the windows hangs and the router is now right beside the thermostat. Is it possible to add more detail to the compile output window as suggested in my last message? It would be useful in general to know more about what the software is doing and would help to specifically address this issue.

**Comment by MauriceDuteau** [comment]
It’s the wifi module on board the device, this module is known to be a poor performer. We will have a new version in the next iteration of our hardware coming out in a month or so. Could you give it a try over RS485, it will be fast and solid. Use the wifi connection once commissioning is done, for intermittent tuning adjustments. 

 

Fandu can add some debug messages as you described, keep an eye out for that in a release coming soon.
