### ISSUE TITLE
TStat10 Watchdog Functionality

### ISSUE THREAD

**Issue by lonerzzz** [temcocontrols/T3000_Building_Automation_System#431]
To handle issues where the TStat10 stops operating or communicating, please add a configurable watchdog to restart the unit if it does not receive communications within N minutes.

**Comment by MauriceDuteau** [comment]
If the Tstat10 is not communicating it will be difficult to send it a command to reset itself, right. We do have some communications watchdogs running on board all our devices, if comms suddenly shuts down where it was active before it will try a reset on the particular adapter, both wifi, RS485 and wire etherent as applicable. Just the communications ports get reinitialized. not the whole device.
